### ISSUE TITLE
[Question, not issue] any plans for prometheus-net 3.1.x (instead of just 2.1.x) support?

### ISSUE THREAD

**Issue by metaleap** [e-conomic/csharp-grpc-prometheus#13]
Right now seems it's built around `netstandard2.0` --- I can still import it in my `netcoreapp2.2` class-library project but won't compile when attempting to use ClientInterceptor, and _will_ compile using the ServerInterceptor but also throw something reflection-related at Startup time.

Might figure out a sub-deps sorta workaround but can't change the class-lib target framework, so was kinda wondering how others would approach this sorta situation..

**Comment by metaleap** [comment]
I think my main issue was that my project was relying on `prometheus-net` 3.1.x whereas yours is based on 2.1.3. Specifically `build` complained about missing assembly reference to provide `ICollectorRegistry` but I reckon the differences between these two prometheus-net "editions" are too vast anyway to reconcile. Feel free to close if irrelevant to your plans/repo! Just changing the title for now.

**Comment by nmbro** [comment]
I don't see a problem in trying to make it work for the newer `promethus-net` is it something you are up for doing? feel free to make a pull-request

**Comment by metaleap** [comment]
Could be possible. Full port is out of scope for current phase of project, but could be feasible for the next phase. If so, will post here or just PR. Cheers!

**Comment by nikitawow** [comment]
Please check MR: https://github.com/e-conomic/csharp-grpc-prometheus/pull/14/files

**Comment by nmbro** [comment]
@metaleap #14 just got merged - will that help you?

**Comment by metaleap** [comment]
@nmbro in theory it "totally would" except the project where this need came up last June just got sniped for good, and apart from it, I have zero .net activities ongoing or planned (or wanted =) --- big props either way, I'm sure it will prove helpful to many. Cheers!
